[package]
name = "rust-sonic-boojum"
version = "0.1.0"
authors = ["alexandre.belling <alexandre.belling@consensys.net>"]
edition = "2018"

[dependencies]
bellman_ce = { path = "../bellman" }
rand = "0.4.0"
num-bigint = "0.2"
